api:
  cors:
    enabled: true
    origins:
    - http://localhost:3000
    - http://localhost:8501
  host: 0.0.0.0
  port: 8000
  timeout: 30
  workers: 4
asset:
  base_currency: EUR
  name: EUR/USD
  quote_currency: USD
  symbol: EURUSD
  type: forex
data:
  markets:
  - nasdaq-100
  model_dir: ./data/models
  processed_dir: ./data/processed
  raw_dir: ./data/raw
  sources:
    alpha_vantage:
      enabled: true
      max_articles_per_day: 2000
    investing_com:
      enabled: true
      max_articles_per_day: 2000
    yahoo_finance:
      enabled: true
      lookback_years: 5
  tickers:
  - EURUSD
  years: 10
gcp:
  bigquery:
    dataset: fpp_data
  cloud_run:
    cpu: 2
    memory: 4Gi
    service_name: fpp-api
  cloud_scheduler:
    job_name: fpp-daily-update
    schedule: 0 2 * * *
    timezone: America/New_York
  project_id: null
  region: us-central1
indicators:
  enabled:
  - SMA
  - RSI
  - MACD
  - BollingerBands
  - ATR
  - Fibonacci
  - PivotPoints
  - Stochastic
  - CCI
  fibonacci_period: 20
  pivot_types:
  - standard
  - fibonacci
logging:
  file:
    backup_count: 5
    max_bytes: 10485760
    path: ./logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
  - console
  - file
  level: INFO
models:
  finbert:
    max_length: 512
    name: ProsusAI/finbert
    quantization: null
  gemma:
    max_length: 8192
    name: google/gemma-2-2b
    quantization: 4bit
  phi3:
    max_length: 4096
    name: microsoft/Phi-3-mini-4k-instruct
    quantization: null
monitoring:
  tensorboard:
    enabled: true
    log_dir: ./logs/tensorboard
  wandb:
    enabled: false
    project: fpp-ssl
prediction:
  buckets:
    1:
      label: large_down
      threshold: <-0.5%
    2:
      label: small_down
      threshold: -0.5% to -0.2%
    3:
      label: flat
      threshold: -0.2% to +0.2%
    4:
      label: small_up
      threshold: +0.2% to +0.5%
    5:
      label: large_up
      threshold: '>+0.5%'
  horizon: 1d
  targets:
  - direction
  - bucket
preprocessing:
  news:
    article_separator: ' [SEP] '
    concat_articles: true
    include_metadata: true
    max_article_length: 2000
    min_length: 50
    normalize_unicode: false
    remove_duplicates: true
    remove_html: true
    remove_urls: true
    use_summary_fallback: true
  prices:
    calc_log_returns: true
    calc_ohlc_returns: true
    calc_volume_change: true
    technical_indicators:
    - sma
    - rsi
    - macd
  sampling:
    date_range_days: 365
    require_both_news_and_price: true
    strategy: random
    target_size: 10000
  sequences:
    format: 'News: {text}; Price: open={open}, high={high}, low={low}, close={close},
      volume={volume}, returns={returns}'
    max_sequence_length: 512
  temporal_alignment: intraday
  ticker_matching:
    min_news_per_ticker: 5
    use_market_fallback: true
    use_ticker_specific: true
project:
  description: SSL-Based Financial Prediction Platform
  name: fpp-ssl
  version: 0.1.0
training:
  fine_tuning:
    batch_size: 16
    epochs: 3
    learning_rate: 2e-5
    lora_alpha: 32
    lora_dropout: 0.1
    lora_r: 8
    method: lora
  incremental:
    batch_size: 16
    epochs: 1
    full_retrain_frequency: monthly
    learning_rate: 1e-5
    method: lora
    update_frequency: daily
  ssl:
    batch_size: 16
    contrastive_temperature: 0.07
    epochs: 2
    gradient_accumulation_steps: 4
    learning_rate: 1e-5
    mlm_probability: 0.15
    warmup_steps: 500
    weight_decay: 0.01
